spring:
  datasource:
    url: jdbc:mysql://localhost:3306/abcd
    hikari:
      username: username
      password: password
#      connection-timeout: 120000
#      max-lifetime: 1800000
#      idle-timeout: 300000
#      maximum-pool-size: 20
#      minimum-idle: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
#  main:
#    allow-bean-definition-overriding: true

#  datasource:
##    url: jdbc:mysql://localhost:3306/rental?useSSL=false
##    &createDatabaseIfNotExist=true
##    username: root
##    password:
#    url: jdbc:mysql://bdf05b57e98b9c:29ed01c9@us-cdbr-east-06.cleardb.net/heroku_92c50516db68778?reconnect=true&useSSL=false&createDatabaseIfNotExist=true
#    username: bdf05b57e98b9c #heroku
#    password: 29ed01c9
#    database: heroku_92c50516db68778
#  validatorInnerData:
##    mongodb:
#      #      user: test
#      #      password: passwordvalue
##      uri: mongodb://localhost:27017
##      database: rental
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        ddl-auto: create
#  rabbitmq:
#    dynamic: true
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest


#rental:
#  rabbitmq:
#    exchange: save-bill-topic
#    queue: save-bill-queue
#    routingkey: save-bill-routing-key
server:
  port: 8900
